/**
 * Builds the printable HTML for one report. Pure string templating — no external
 * network fetches, no user-controlled URLs are ever loaded (SSRF surface is closed by
 * design: this module only ever receives already-fetched JSON payloads).
 */

function escapeHtml(value) {
  return String(value)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;");
}

function renderCoreNumberRow(label, metric) {
  if (!metric) return "";
  const master = metric.master_number ? ` <span class="badge">Master</span>` : "";
  const karmic = (metric.flags || []).some((f) => f.code === "KARMIC_DEBT")
    ? ` <span class="badge badge-karmic">Karmic Debt</span>`
    : "";
  return `<tr><td>${escapeHtml(label)}</td><td class="value">${escapeHtml(metric.display_value)}${master}${karmic}</td></tr>`;
}

function renderCoverPage({ person, profile, report }) {
  const name = person
    ? `${escapeHtml(person.birth_first_names || "")} ${escapeHtml(person.birth_last_name || "")}`.trim()
    : "";
  const birthDate = person?.birth_date ? escapeHtml(person.birth_date) : "";
  const core = profile?.core_numbers || {};
  return `
    <section class="cover page-break-after">
      <div class="cover-eyebrow">NUMRA — numra-canonical v${escapeHtml(report.calculation_version || "1.0.0")}</div>
      <h1 class="cover-title">${name || "Numerological Profile"}</h1>
      <div class="cover-sub">${birthDate}</div>
      <table class="core-table">
        ${renderCoreNumberRow("Life Path", core.life_path)}
        ${renderCoreNumberRow("Expression", core.expression)}
        ${renderCoreNumberRow("Soul Urge", core.soul_urge)}
        ${renderCoreNumberRow("Personality", core.personality)}
      </table>
      <div class="cover-footer">
        Report type ${escapeHtml(report.report_type)} · Knowledge v${escapeHtml(report.knowledge_version)} ·
        Prompt ${escapeHtml(report.prompt_version)} · Generated by ${escapeHtml(report.model_provider)}/${escapeHtml(report.model_name)}
      </div>
    </section>`;
}

function renderToc(sections) {
  const items = sections
    .map((s) => `<li><span class="toc-title">${escapeHtml(s.title)}</span><span class="toc-dots"></span><span class="toc-num">${s.order_index + 1}</span></li>`)
    .join("");
  return `<section class="toc page-break-after"><h2>Contents</h2><ol class="toc-list">${items}</ol></section>`;
}

function renderSection(section) {
  const paragraphs = section.text
    .split("\n\n")
    .filter((p) => p.trim().length > 0)
    .map((p) => `<p>${escapeHtml(p)}</p>`)
    .join("\n");
  return `
    <section class="report-section">
      <h2>${section.order_index + 1}. ${escapeHtml(section.title)}</h2>
      ${paragraphs}
    </section>`;
}

function renderAppendix({ profile }) {
  const core = profile?.core_numbers || {};
  const rows = [
    ["Life Path", core.life_path],
    ["Birthday", core.birthday],
    ["Attitude", core.attitude],
    ["Expression", core.expression],
    ["Soul Urge", core.soul_urge],
    ["Personality", core.personality],
    ["Maturity", core.maturity],
    ["Balance", core.balance],
  ]
    .map(([label, metric]) => renderCoreNumberRow(label, metric))
    .join("");
  return `
    <section class="report-section appendix">
      <h2>Calculation Appendix</h2>
      <p class="methodology-note">
        Every numeric value in this report was produced by NUMRA's deterministic
        calculation engine (${escapeHtml(profile?.calculation_system || "numra-canonical")}
        v${escapeHtml(profile?.calculation_version || "1.0.0")}) — never estimated or
        invented by language-model text generation. See the web application's
        Calculation Inspector for the full step-by-step trace of every metric below.
      </p>
      <table class="core-table">${rows}</table>
    </section>`;
}

export function renderReportHtml({ report, profile, person }) {
  const sections = [...(report.sections || [])].sort((a, b) => a.order_index - b.order_index);
  return `<!doctype html>
<html lang="${escapeHtml(report.language || "de")}">
<head>
<meta charset="utf-8" />
<title>${escapeHtml(person?.birth_first_names || "NUMRA")} — NUMRA Report</title>
<style>${STYLES}</style>
</head>
<body>
${renderCoverPage({ person, profile, report })}
${renderToc(sections)}
${sections.map(renderSection).join("\n")}
${renderAppendix({ profile })}
</body>
</html>`;
}

const STYLES = `
  @page { size: A4; margin: 24mm 18mm; }
  * { box-sizing: border-box; }
  body {
    font-family: Georgia, "Times New Roman", serif;
    color: #201f26;
    background: #ffffff;
    line-height: 1.6;
    font-size: 11.5pt;
  }
  h1, h2 { font-family: Georgia, serif; color: #3a2f12; }
  .page-break-after { page-break-after: always; }
  .cover { text-align: center; padding-top: 30%; }
  .cover-eyebrow { letter-spacing: 0.12em; text-transform: uppercase; color: #8f6b3e; font-size: 10pt; }
  .cover-title { font-size: 30pt; margin: 12pt 0 4pt; }
  .cover-sub { color: #555; margin-bottom: 24pt; }
  .core-table { margin: 0 auto; border-collapse: collapse; }
  .core-table td { padding: 4pt 12pt; border-bottom: 1px solid #e5ddc8; text-align: left; }
  .core-table td.value { font-weight: bold; color: #8f6b3e; }
  .badge { font-size: 8pt; border: 1px solid #8f6b3e; border-radius: 3pt; padding: 1pt 4pt; margin-left: 4pt; }
  .badge-karmic { border-color: #604b72; color: #604b72; }
  .cover-footer { margin-top: 24pt; font-size: 9pt; color: #777; }
  .toc-list { list-style: none; padding: 0; }
  .toc-list li { display: flex; align-items: baseline; margin: 6pt 0; }
  .toc-dots { flex: 1; border-bottom: 1px dotted #ccc; margin: 0 6pt; }
  .report-section { page-break-inside: avoid; margin-bottom: 18pt; }
  .methodology-note { font-style: italic; color: #555; }
`;
